-- user table
CREATE TABLE USER
   ("PID" NUMBER NOT NULL ENABLE,
	"NAME" VARCHAR2(20) NOT NULL ENABLE,
	"GENDER" VARCHAR2(10) NOT NULL ENABLE,
	"AGE" NUMBER NOT NULL ENABLE,
	"PHONE" VARCHAR2(15) NOT NULL ENABLE,
	"ADDRESS" VARCHAR2(250) NOT NULL ENABLE,
	"DISEASE" VARCHAR2(15) NOT NULL ENABLE,
	"STATUS" VARCHAR2(100) NOT NULL ENABLE,
	"BUILDING" VARCHAR2(4) NOT NULL ENABLE,
	"ROOMNO" VARCHAR2(10) NOT NULL ENABLE,
	"ROOMTYPE" VARCHAR2(10) NOT NULL ENABLE,
	"PRICE" NUMBER NOT NULL ENABLE,
	"TIME" VARCHAR2(20) NOT NULL ENABLE,
	CONSTRAINT "REGISTRATION_PK" PRIMARY KEY ("PID") ENABLE
);

-- user_info table
CREATE TABLE USER_INFO (
  "ID" NUMBER,
	"NAME" VARCHAR2(20),
	"PASSWORD" VARCHAR2(20),
	"POSITION" VARCHAR2(20),
	 CONSTRAINT "USER_INFO_PK" PRIMARY KEY ("ID") ENABLE
);

-- staff table
CREATE TABLE STAFF (
  "ID" NUMBER,
	"NAME" VARCHAR2(20),
	"SEX" VARCHAR2(7),
	"POSITION" VARCHAR2(12),
	"SALARY" NUMBER,
	"PHONE" NUMBER,
	"ADDRESS" VARCHAR2(250),
	 CONSTRAINT "STAFF_PK" PRIMARY KEY ("ID") ENABLE
);
