-- user table
CREATE TABLE USER
   ("PID" NUMBER NOT NULL ENABLE,
	"NAME" VARCHAR2(20) NOT NULL ENABLE,
	"GENDER" VARCHAR2(10) NOT NULL ENABLE,
	"AGE" NUMBER NOT NULL ENABLE,
	"PHONE" VARCHAR2(15) NOT NULL ENABLE,
	"ADDRESS" VARCHAR2(250) NOT NULL ENABLE,
	"DISEASE" VARCHAR2(15) NOT NULL ENABLE,
	"STATUS" VARCHAR2(100) NOT NULL ENABLE,
	"BUILDING" VARCHAR2(4) NOT NULL ENABLE,
	"ROOMNO" VARCHAR2(10) NOT NULL ENABLE,
	"ROOMTYPE" VARCHAR2(10) NOT NULL ENABLE,
	"PRICE" NUMBER NOT NULL ENABLE,
	"TIME" VARCHAR2(20) NOT NULL ENABLE,
	CONSTRAINT "REGISTRATION_PK" PRIMARY KEY ("PID") ENABLE
);
